version: "3.8"

services:
  backend:
    container_name: backend
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/task-management-db
      SPRING_DATASOURCE_USERNAME: docker_user
      SPRING_DATASOURCE_PASSWORD: docker_password
      SPRING_PROFILES_ACTIVE: prod
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s

  postgres:
    container_name: postgres
    image: postgres:16.1
    environment:
      POSTGRES_DB: task-management-db
      POSTGRES_USER: docker_user
      POSTGRES_PASSWORD: docker_password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "--quiet" ]
      interval: 1s
      timeout: 5s
      retries: 10
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s

volumes:
  postgres: